[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    EditThisPage = "Edit this page on"

[zh]
  languageName = "Chinese"
  contentDir = "content/zh"
  weight = 10
  [zh.params]
    languageISO = "ZH"
    EditThisPage = "改进文档"
